nameOverride: ""
fullnameOverride: ""

server:
  image:
    # repository: ubercadence/server
    repository: banzaicloud/cadence-server
    tag: 0.5.9
    pullPolicy: IfNotPresent

  # Global default settings (can be overridden per service)
  replicaCount: 1
  metrics:
    prometheus:
      timerType: histogram
  podAnnotations: {}
    # Annotation to enable Prometheus scrape functionality.
    # prometheus.io/scrape: 'true'
    # prometheus.io/port: '9090'
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  config:
    logLevel: "debug,info"
    numHistoryShards: 1000
    persistence:
      default:
        driver: "" # cassandra or sql

        cassandra:
          hosts: []
          # port: 9042
          keyspace: cadence
          consistency: One
          user: ""
          password: ""

        sql:
          driver: "" # mysql
          host: ""
          # port: 3306
          database: cadence
          user: ""
          password: ""

      visibility:
        driver: "" # cassandra or sql

        cassandra:
          hosts: []
          # port: 9042
          keyspace: cadence_visibility
          consistency: One
          user: ""
          password: ""

        sql:
          driver: "" # mysql
          host: ""
          # port: 3306
          database: cadence_visibility
          user: ""
          password: ""

  frontend:
    # replicaCount: 1
    service:
      type: ClusterIP
      port: 7933
    metrics:
      prometheus: {}
        # timerType: histogram
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  history:
    # replicaCount: 1
    service:
      # type: ClusterIP
      port: 7934
    metrics:
      prometheus: {}
        # timerType: histogram
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  matching:
    # replicaCount: 1
    service:
      # type: ClusterIP
      port: 7935
    metrics:
      prometheus: {}
        # timerType: histogram
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  worker:
    # replicaCount: 1
    service:
      # type: ClusterIP
      port: 7939
    metrics:
      prometheus: {}
        # timerType: histogram
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

web:
  enabled: true

  replicaCount: 1

  image:
    repository: ubercadence/web
    tag: 3.3.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    annotations: {}
    # loadBalancerIP:

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: traefik
      # ingress.kubernetes.io/ssl-redirect: "false"
      # traefik.frontend.rule.type: PathPrefix
    hosts:
      - "/"
      # - "domain.com/xyz"
      # - "domain.com"
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}


cassandra:
  enabled: true
  image:
    repo: cassandra
    tag: 3.11.3
    pullPolicy: IfNotPresent
  config:
    cluster_size: 1
    ports:
      cql: 9042

mysql:
  enabled: false
  imageTag: "5.7.26"
  service:
    port: 3306
  mysqlUser: cadence
  # TODO: support secrets
  mysqlPassword: cadence
  initializationFiles:
    user.sql: |-
      GRANT ALL PRIVILEGES ON *.* TO 'cadence'@'%';
